site_name: Green API
repo_name: green-api/docs 
repo_url: https://github.com/green-api/docs
edit_uri: edit/master/ru/docs/
site_dir: build
site_url: https://green-api.com

nav:
  - "Home":
    - Home: "/en"
  - "Blog":
    - Blog: "/en/blog/index.html"
  - "Documents": 
    - 'Index': 'index.md'
    - 'Quick start':
        - 'Before you start': 'before-start.md'
        - 'Execute requests': 'request-format.md'
        - 'Postman collection': 'postman-collection.md'
    #     - 'Send text message': 'api/sending/SendMessage.md'
    #     - 'Send image': 'api/sending/SendMessage.md'
    #     - 'Get outgoing message status': 'api/sending/SendMessage.md'
    #     - 'Как написать чат-бота': 'api/sending/SendMessage.md'
    - 'API documents':
        - 'Overview': 'api/index.md'
        - 'Account':
            - 'Account - overview': 'api/account/index.md'
            - 'Get account settings': 'api/account/GetSettings.md'
            - 'Set account settings': 'api/account/SetSettings.md'
            - 'Set system proxy': 'api/account/SetSystemProxy.md'
            - 'Get account state': 'api/account/GetStateInstance.md'
            - 'Get account connection status': 'api/account/GetStatusInstance.md'
            - 'Reboot account': 'api/account/Reboot.md'
            - 'Logout account': 'api/account/Logout.md'
            - 'Get QR code': 'api/account/QR.md'
            - 'Get QR code via websocket': 'api/account/Scanqrcode.md'
            - 'Set profile picture': 'api/account/SetProfilePicture.md'
        - 'Sending':
            - 'Sending - overview': 'api/sending/index.md'
            - 'Send text': 'api/sending/SendMessage.md'
            - 'Send Buttons': 'api/sending/SendButtons.md'
            - 'Send Template Buttons': 'api/sending/SendTemplateButtons.md'
            - 'Send List Message': 'api/sending/SendListMessage.md'
            - 'Send video, audio, image, document': 'api/sending/SendFileByUpload.md'
            - 'Send video, audio, image, document via URL': 'api/sending/SendFileByUrl.md'
            - 'Send location': 'api/sending/SendLocation.md'
            - 'Send contact': 'api/sending/SendContact.md'
            - 'Send link': 'api/sending/SendLink.md'
        - 'Receiving':
            - 'Conception': 'api/receiving/index.md'
            - 'HTTP API':
                - 'HTTP API technology': 'api/receiving/technology-http-api.md'
                - 'Receive notification': 'api/receiving/technology-http-api/ReceiveNotification.md'
                - 'Delete notification': 'api/receiving/technology-http-api/DeleteNotification.md'
            - 'Webhook Endpoint':
                - 'Webhook Endpoint technology': 'api/receiving/technology-webhook-endpoint.md'
            - 'Incoming notifications format':
                - 'Overview': 'api/receiving/notifications-format/index.md'
                - 'Incoming mesage':
                    - 'Incoming messages': 'api/receiving/notifications-format/incoming-message/Webhook-IncomingMessageReceived.md'
                    - 'Text': 'api/receiving/notifications-format/incoming-message/TextMessage.md'
                    - 'Text with URL': 'api/receiving/notifications-format/incoming-message/ExtendedTextMessage.md'
                    - 'Video, audio, image, document': 'api/receiving/notifications-format/incoming-message/ImageMessage.md'
                    - 'Location': 'api/receiving/notifications-format/incoming-message/LocationMessage.md'
                    - 'Contact': 'api/receiving/notifications-format/incoming-message/ContactMessage.md'
                    - 'Incoming buttons message': 'api/receiving/notifications-format/incoming-message/ButtonsMessage.md'
                    - 'Selection list incoming message': 'api/receiving/notifications-format/incoming-message/ListMessage.md'
                    - 'Template buttons incoming message': 'api/receiving/notifications-format/incoming-message/TemplateMessage.md'
                    - '(deprecated) Quoted message': 'api/receiving/notifications-format/incoming-message/QuotedMessage.md'
                - 'Selecting buttons':
                    - 'Simple button selection ': 'api/receiving/notifications-format/selected-buttons/ButtonsResponseMessage.md'
                    - 'Template button selection': 'api/receiving/notifications-format/selected-buttons/TemplateButtonsReplyMessage.md'
                    - 'List element selection': 'api/receiving/notifications-format/selected-buttons/ListResponseMessage.md'                
                - 'Outgoing message':
                    - 'Message sent from phone': 'api/receiving/notifications-format/outgoing-message/OutgoingMessage.md'
                    - 'Message sent via API': 'api/receiving/notifications-format/outgoing-message/OutgoingApiMessage.md'
                    - 'Outgoing message status': 'api/receiving/notifications-format/outgoing-message/OutgoingMessageStatus.md'
                - 'Others':
                    - 'Account status': 'api/receiving/notifications-format/StateInstanceChanged.md'
                    - 'Device status': 'api/receiving/notifications-format/DeviceInfo.md'
                    - 'Contact avatar': 'api/receiving/notifications-format/AvatarInfo.md'
                    - 'Account socket status': 'api/receiving/notifications-format/StatusInstanceChanged.md'
                    - 'Incoming call': 'api/receiving/notifications-format/IncomingCall.md'
                - 'Objects':
                    - 'Incoming webhooks types': 'api/receiving/notifications-format/type-webhook.md'
            - 'Get files':
                - 'Download file from incoming message': 'api/receiving/files/DownloadFile.md'
        - 'Journals':
            - 'Journals - review': 'api/journals/index.md'
            - 'Get chat history': 'api/journals/GetChatHistory.md'
            - 'Get incoming messages journal': 'api/journals/LastIncomingMessages.md'
            - 'Get outgoing messages journal': 'api/journals/LastOutgoingMessages.md'
        - 'Queues':
            - 'Queues - overview': 'api/queues/index.md'
            - 'Show messages queue': 'api/queues/ShowMessagesQueue.md'
            - 'Clear messages queue': 'api/queues/ClearMessagesQueue.md'
        - 'Groups':
            - 'Groups - overview': 'api/groups/index.md'
            - 'Create group': 'api/groups/CreateGroup.md'
            - 'Change group name': 'api/groups/UpdateGroupName.md'
            - 'Get group data': 'api/groups/GetGroupData.md'
            - 'Add group participant': 'api/groups/AddGroupParticipant.md'
            - 'Delete group participant': 'api/groups/RemoveGroupParticipant.md'
            - 'Set group admin rights': 'api/groups/SetGroupAdmin.md'
            - 'Remove group admin rights': 'api/groups/RemoveAdmin.md'
            - 'Set group picture': 'api/groups/SetGroupPicture.md'
            - 'Leave group': 'api/groups/LeaveGroup.md'
        - 'Read mark':
            - 'Read mark - overview': 'api/marks/index.md'
            - 'Mark chat as read': 'api/marks/ReadChat.md'
        - 'Device (phone)':
            - 'Device - overview': 'api/phone/index.md'
            - 'Get device info': 'api/phone/GetDeviceInfo.md'
        - 'Service methods':
            - 'Service methods - overview': 'api/service/index.md'
            - 'Check WhatsApp availability': 'api/service/CheckWhatsapp.md'
            - 'Get avatar': 'api/service/GetAvatar.md'
            - '(deprecated) Get avatar asynchronously': 'api/service/GetAvatarAsync.md'
            - 'Get contacts': 'api/service/GetContacts.md'
            - 'Get Contact Info': 'api/service/GetContactInfo.md'
            - 'Delete message': 'api/service/deleteMessage.md'
            - 'Archive Chat': 'api/service/archiveChat.md'
            - 'UnarchiveChat': 'api/service/unarchiveChat.md'
            - 'Change the settings of disappearing chat messages': 'api/service/SetDisappearingChat.md'
        - 'Others':
            - 'Chat Id': 'api/chat-id.md'
            - 'Messages sending delay': 'api/send-messages-delay.md'
            - 'Common errors': 'api/common-errors.md'
    - 'FAQ':
        - 'FAQ': 'faq/index.md'
        - 'How to protect number from ban?': 'faq/how-to-protect-number-from-ban.md'
        - 'If your number is blocked': 'faq/if-your-number-is-blocked.md'
  - Releases: 
        - "Overview": 'release/index.md'
        - 'GREEN-API releases': 
          - '5.44.19.39 dd. 19.10.2022': 'release/5.44.19.39.md'
          - '5.44.18.74 dd. 20.09.2022': 'release/5.44.18.74.md'
          - '5.44.18.28 dd. 13.09.2022': 'release/5.44.18.28.md'
          - '5.43.17.130 dd. 23.08.2022': 'release/5.43.17.130.md'
          - '5.43.16.63 dd. 09.08.2022': 'release/5.43.16.63.md'
  - SDK: 
        - "Overview": 'sdk/index.md'
        - 'GREEN-API SDK': 
          - 'Python WhatsApp Library': 
            - 'Overview': 'sdk/python/index.md'
            - 'sdk/python/sendmessage.md'
            - 'sdk/python/sendfilebyurl.md'
            - 'sdk/python/sendfilebyupload.md'
            - 'sdk/python/creategroup.md'
            - 'sdk/python/receiveNotification.md'
            - 'sdk/python/fullmethods.md'    
      # - 'Integration':
    #     - '1С': 'api/sending/SendMessage.md'
    #     - 'NodeJS': 'api/sending/SendMessage.md'
    #     - 'HTML': 'api/sending/SendMessage.md'
    
theme:
  name: material
  custom_dir: overrides

   # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/green-api-logo.png

extra_css:
  - stylesheets/styles.css
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search:
      lang:
        - en
        - ru
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink:  "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
