site_name: Green API
repo_name: green-api/docs 
repo_url: https://github.com/green-api/docs
edit_uri: edit/master/ru/docs/
site_dir: build
site_url: https://green-api.com

nav:
  - "Главная":
    - Главная: "/"
  - "Блог":
    - Блог: "/blog/index.html"
  - "Документация": 
    - 'Оглавление': 'index.md'
    - 'Быстрый старт':
        - 'Перед началом работы': 'before-start.md'
        - 'Выполнение запросов': 'request-format.md'
        - 'Коллекция Postman': 'postman-collection.md'
    #     - 'Как отправить текстовое сообщение': 'api/sending/SendMessage.md'
    #     - 'Как отправить картинку': 'api/sending/SendMessage.md'
    #     - 'Как получить статус отправленного сообщения': 'api/sending/SendMessage.md'
    #     - 'Как написать чат-бота': 'api/sending/SendMessage.md'
    - 'Документация API':
        - 'Обзор': 'api/index.md'
        - 'Аккаунт':
            - 'Аккаунт обзор': 'api/account/index.md'
            - 'Получить настройки аккаунта': 'api/account/GetSettings.md'
            - 'Установить настройки аккаунта': 'api/account/SetSettings.md'
            - 'Установить системный прокси': 'api/account/SetSystemProxy.md'
            - 'Получить состояние аккаунта': 'api/account/GetStateInstance.md'
            - 'Получить состояние соединения аккаунта': 'api/account/GetStatusInstance.md'
            - 'Перезапустить аккаунт': 'api/account/Reboot.md'
            - 'Разлогинить аккаунт': 'api/account/Logout.md'
            - 'Получить QR-код': 'api/account/QR.md'
            - 'Получить QR-код через websocket': 'api/account/Scanqrcode.md'
            - 'Установить аватар аккаунта': 'api/account/SetProfilePicture.md'
        - 'Отправка':
            - 'Отправка обзор': 'api/sending/index.md'
            - 'Отправить текст': 'api/sending/SendMessage.md'
            - 'Отправить обычные кнопки': 'api/sending/SendButtons.md'
            - 'Отправить шаблонные кнопки': 'api/sending/SendTemplateButtons.md'
            - 'Отправить список выбора': 'api/sending/SendListMessage.md'
            - 'Отправить видео, аудио, изображение, документ': 'api/sending/SendFileByUpload.md'
            - 'Отправить видео, аудио, изображение, документ по URL': 'api/sending/SendFileByUrl.md'
            - 'Отправить геолокацию': 'api/sending/SendLocation.md'
            - 'Отправить контакт': 'api/sending/SendContact.md'
            - 'Отправить ссылку': 'api/sending/SendLink.md'
        - 'Получение':
            - 'Концепция': 'api/receiving/index.md'
            - 'HTTP API':
                - 'Технология HTTP API': 'api/receiving/technology-http-api.md'
                - 'Получить уведомление': 'api/receiving/technology-http-api/ReceiveNotification.md'
                - 'Удалить уведомление': 'api/receiving/technology-http-api/DeleteNotification.md'
            - 'Webhook Endpoint':
                - 'Технология Webhook Endpoint': 'api/receiving/technology-webhook-endpoint.md'
            - 'Формат входящих уведомлений':
                - 'Обзор': 'api/receiving/notifications-format/index.md'
                - 'Входящее сообщение':
                    - 'Входящие сообщения': 'api/receiving/notifications-format/incoming-message/Webhook-IncomingMessageReceived.md'
                    - 'Текст': 'api/receiving/notifications-format/incoming-message/TextMessage.md'
                    - 'Текст или текст с URL': 'api/receiving/notifications-format/incoming-message/ExtendedTextMessage.md'
                    - 'Видео, аудио, изображение, документ': 'api/receiving/notifications-format/incoming-message/ImageMessage.md'
                    - 'Геопозиция': 'api/receiving/notifications-format/incoming-message/LocationMessage.md'
                    - 'Контакт': 'api/receiving/notifications-format/incoming-message/ContactMessage.md'
                    - 'Входящее сообщение с кнопками': 'api/receiving/notifications-format/incoming-message/ButtonsMessage.md'
                    - 'Входящее сообщение со списком выбора': 'api/receiving/notifications-format/incoming-message/ListMessage.md'
                    - 'Входящее сообщение с шаблонными кнопками': 'api/receiving/notifications-format/incoming-message/TemplateMessage.md'
                    - '(не используется) Cообщение с цитатой': 'api/receiving/notifications-format/incoming-message/QuotedMessage.md'
                - 'Выбор кнопок':
                    - 'Выбор обычной кнопки': 'api/receiving/notifications-format/selected-buttons/ButtonsResponseMessage.md'
                    - 'Выбор шаблонной кнопки': 'api/receiving/notifications-format/selected-buttons/TemplateButtonsReplyMessage.md'
                    - 'Выбор элемента списка': 'api/receiving/notifications-format/selected-buttons/ListResponseMessage.md'
                - 'Отправленное сообщение':
                    - 'Отправленное с телефона сообщение': 'api/receiving/notifications-format/outgoing-message/OutgoingMessage.md'
                    - 'Отправленное сообщение через API': 'api/receiving/notifications-format/outgoing-message/OutgoingApiMessage.md'
                    - 'Статус отправленного сообщения': 'api/receiving/notifications-format/outgoing-message/OutgoingMessageStatus.md'
                - 'Прочие':
                    - 'Статус аккаунта': 'api/receiving/notifications-format/StateInstanceChanged.md'
                    - 'Статус устройства': 'api/receiving/notifications-format/DeviceInfo.md'
                    - 'Аватар контакта': 'api/receiving/notifications-format/AvatarInfo.md'
                    - 'Статус сокета аккаунта': 'api/receiving/notifications-format/StatusInstanceChanged.md'
                    - 'Входящий звонок': 'api/receiving/notifications-format/IncomingCall.md'
                - 'Объекты':
                    - 'Типы входящих уведомлений': 'api/receiving/notifications-format/type-webhook.md'
            - 'Получение файлов':
                - 'Скачать файл из входящего сообщения': 'api/receiving/files/DownloadFile.md'
        - 'Журналы':
            - 'Журналы обзор': 'api/journals/index.md'
            - 'Получить историю сообщений чата': 'api/journals/GetChatHistory.md'
            - 'Получить журнал входящих сообщений': 'api/journals/LastIncomingMessages.md'
            - 'Получить журнал отправленных сообщений': 'api/journals/LastOutgoingMessages.md'
        - 'Очереди':
            - 'Очереди обзор': 'api/queues/index.md'
            - 'Получить очередь сообщений к отправке': 'api/queues/ShowMessagesQueue.md'
            - 'Очистить очередь сообщений к отправке': 'api/queues/ClearMessagesQueue.md'
        - 'Группы':
            - 'Группы обзор': 'api/groups/index.md'
            - 'Создать группу': 'api/groups/CreateGroup.md'
            - 'Изменить имя группы': 'api/groups/UpdateGroupName.md'
            - 'Получить информацию о группе': 'api/groups/GetGroupData.md'
            - 'Добавить участника в группу': 'api/groups/AddGroupParticipant.md'
            - 'Удалить участника из группы': 'api/groups/RemoveGroupParticipant.md'
            - 'Назначить права администратора группы': 'api/groups/SetGroupAdmin.md'
            - 'Отозвать права администратора группы': 'api/groups/RemoveAdmin.md'
            - 'Установить Аватар группы': 'api/groups/SetGroupPicture.md'
            - 'Выйти из группы': 'api/groups/LeaveGroup.md'
        - 'Отметка прочтения':
            - 'Отметка прочтения обзор': 'api/marks/index.md'
            - 'Отметить чат прочитанным': 'api/marks/ReadChat.md'
        - 'Устройство (телефон)':
            - 'Устройство обзор': 'api/phone/index.md'
            - 'Получить информацию об устройстве': 'api/phone/GetDeviceInfo.md'
        - 'Сервисные методы':
            - 'Сервисные методы обзор': 'api/service/index.md'
            - 'Проверить наличие WhatsApp': 'api/service/CheckWhatsapp.md'
            - 'Получить аватар': 'api/service/GetAvatar.md'
            - '(не используется) Получить аватар асинхронно': 'api/service/GetAvatarAsync.md'
            - 'Получить контакты': 'api/service/GetContacts.md'
            - 'Получить информацию о контакте': 'api/service/GetContactInfo.md'
            - 'Удалить сообщение': 'api/service/deleteMessage.md'
            - 'Архивировать чат': 'api/service/archiveChat.md'
            - 'Разархивировать чат': 'api/service/unarchiveChat.md'
            - 'Изменить настройки исчезающих сообщений чата ': 'api/service/SetDisappearingChat.md'
        - 'Прочее':
            - 'Идентификатор чата': 'api/chat-id.md'
            - 'Интервал отправки сообщений': 'api/send-messages-delay.md'
            - 'Стандартные ошибки': 'api/common-errors.md'
    - 'FAQ':
        - 'Все вопросы': 'faq/index.md'
        - 'Как защитить номер от бана?': 'faq/how-to-protect-number-from-ban.md'
        - 'Если ваш номер заблокирован': 'faq/if-your-number-is-blocked.md'
  - Релизы: 
        - "Оглавление": 'release/index.md'
        - 'Список релизов': 
          - '5.44.19.39 от 11.10.2022': 'release/5.44.19.39.md'
          - '5.44.18.74 от 20.09.2022': 'release/5.44.18.74.md'
          - '5.44.18.28 от 13.09.2022': 'release/5.44.18.28.md'
          - '5.43.17.130 от 23.08.2022': 'release/5.43.17.130.md'
          - '5.43.16.63 от 09.08.2022': 'release/5.43.16.63.md'
  - SDK: 
        - "Оглавление": 'sdk/index.md'
        - 'Список SDK': 
          - 'Python WhatsApp Library': 
            - 'Обзор': 'sdk/python/index.md'
            - 'sdk/python/sendmessage.md'
            - 'sdk/python/sendfilebyurl.md'
            - 'sdk/python/sendfilebyupload.md'
            - 'sdk/python/creategroup.md'
            - 'sdk/python/receiveNotification.md'
            - 'sdk/python/fullmethods.md'
    # - 'Интеграция':
    #     - '1С': 'api/sending/SendMessage.md'
    #     - 'NodeJS': 'api/sending/SendMessage.md'
    #     - 'HTML': 'api/sending/SendMessage.md'
    
theme:
  name: material
  custom_dir: overrides

   # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ru
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/green-api-logo.png

extra_css:
  - stylesheets/styles.css
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search:
      lang:
        - en
        - ru
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink:  "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde